version: "3.1"

services:
  # Test production image
  # web:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:example@db:5432/citizen-science

  db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: citizen-science
    volumes:
      - database-data:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4:8.4
    ports:
      - 6434:80
    environment:
      PGADMIN_DEFAULT_EMAIL: local@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  database-data:
  pgadmin-data: