version: "3.7"

services:
  citizen-science-app:
    image: $IMAGE
    ports:
      - 3000:3000
    healthcheck:
      test: curl -sS 127.0.0.1:3000 || exit 1
      interval: 5s
    environment:
      DATABASE_URL: postgresql://postgres:$POSTGRES_PASSWORD@citizen-science-db:5432/citizen-science
      AUTH0_SECRET: $AUTH0_SECRET
      AUTH0_BASE_URL: $AUTH0_BASE_URL
      AUTH0_ISSUER_BASE_URL: $AUTH0_ISSUER_BASE_URL
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET
      NEXT_PUBLIC_TINA_CLIENT_ID: $TINA_CLIENT_ID
      TINA_TOKEN: $TINA_TOKEN
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
    volumes:
      - citizen-science-tei-corpus:/app/tei-corpus
      - ./ssh-config:/home/nextjs/.ssh
      - ./gitconfig:/home/nextjs/.gitconfig
  
  citizen-science-db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: citizen-science
    volumes:
      - citizen-science-database-data:/var/lib/postgresql/data/


volumes:
  citizen-science-database-data:
  citizen-science-tei-corpus:

networks:
  default:
    driver: bridge
    driver_opts: 
      com.docker.network.driver.mtu: 1450