version: "3.7"

services:
  citizen-science-app:
    image: $IMAGE
    ports:
      - 3000:3000
    healthcheck:
      test: curl -sS 127.0.0.1:3000 || exit 1
      interval: 5s
    environment:
      DATABASE_URL: postgresql://postgres:$POSTGRES_PASSWORD@citizen-science-db:5432/citizen-science
      AUTH0_SECRET: $AUTH0_SECRET
      AUTH0_BASE_URL: $AUTH0_BASE_URL
      AUTH0_ISSUER_BASE_URL: $AUTH0_ISSUER_BASE_URL
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET
      NEXT_PUBLIC_TINA_CLIENT_ID: $TINA_CLIENT_ID
      TINA_TOKEN: $TINA_TOKEN
      NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: $NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
    volumes:
      - citizen-science-tei-corpus:/app/tei-corpus
      - citizen-science-pino-logs:/app/pino-logs
      - ./ssh-config:/home/nextjs/.ssh
      - ./gitconfig:/home/nextjs/.gitconfig
    networks:
      - citizen_science
  
  citizen-science-db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: citizen-science
    volumes:
      - citizen-science-database-data:/var/lib/postgresql/data/
    networks:
      - citizen_science
    command: >
      -c work_mem=3072MB
  

  # Source: https://github.com/ixc/restic-pg-dump-docker
  restic-backup:
    image: interaction/restic-pg-dump:d893de06022febc1048fde1c4d54f7852b7bafab
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: $RESTIC_BACKUP_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $RESTIC_BACKUP_AWS_SECRET_ACCESS_KEY
      BACKUP_SCHEDULE: '25 * * * *'  # Hourly at minute 25
      # PRUNE_SCHEDULE: '0 14 * * 0'  # Sunday midnight, AEST. Use '' to disable.
      PGHOST: citizen-science-db
      PGPASSWORD: $POSTGRES_PASSWORD
      # PGPORT: 5432
      PGUSER: postgres
      # RESTIC_KEEP_HOURLY: 24
      # RESTIC_KEEP_DAILY: 7
      # RESTIC_KEEP_WEEKLY: 4
      # RESTIC_KEEP_MONTHLY: 12
      RESTIC_PASSWORD: $RESTIC_BACKUP_PASSWORD
      RESTIC_REPOSITORY: $RESTIC_BACKUP_REPOSITORY
    networks:
      - citizen_science


volumes:
  citizen-science-database-data:
  citizen-science-tei-corpus:
  citizen-science-pino-logs:

networks:
  citizen_science:
    driver: overlay
    driver_opts: 
      com.docker.network.driver.mtu: 1450